library(Seurat)
library(dplyr)
library(Matrix)
library(harmony)
library(cowplot)
library(ggplot2)
rm(blood)
A1<-c("Sell","Dapl1","Ccr7","Lef1","Il7r")
A2<-c("Foxp3","Il2ra","Ikzf2","Ctla4","Tnfrsf4","Tnfrsf18")
A3<-c("S100a4","S100a6","Cd44","S100a11","Itgb1","Ahnak")
A4<-c("Tbx21","Ifng","Xcl1","Nkg7","Ccl5")
A5<-c("Tmem176a","Tmem176b","Il17a","Rorc")
A6<-c("Pdcd1","Cxcr5","Tox2","Tox","Tnfsf8","Icos","Cd40lg")
blood <-AddModuleScore(PP.combined, features= list(A1, A2, A3,A4,A5,A6), name=c("Tn", "Treg", "Tm","Th1","Th17","Tfh"))
blood <-AddModuleScore(SP9w, features= list(A1, A2, A3,A4,A5,A6), name=c("Tn", "Treg", "Tm","Th1","Th17","Tfh"))
blood <-AddModuleScore(SP10d, features= list(A1, A2, A3,A4,A5,A6), name=c("Tn", "Treg", "Tm","Th1","Th17","Tfh"))
t1<-FetchData(blood,vars=c("Tn1", "Treg2", "Tm3","Th14","Th175","Tfh6","ident","orig.ident"))
VlnPlot(blood, features = c("Tn1","Treg2","Tm3","Th14","Th175","Tfh6"), stack=T,pt.size= 0, direction = "horizontal",x.lab = '', y.lab = '')+theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
